name = "NEATJulia"
uuid = "5403864b-411f-4ea8-8fd4-9976b8531895"
authors = ["RithvikReddyAdapa <adaparithvikreddy@gmail.com> and contributors"]
version = "3.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
